/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 90507
 */
public class ogretmen_giris_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form ogretmen_giris_ekrani
     */
    public ogretmen_giris_ekrani() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ogretmen_panel = new javax.swing.JPanel();
        ogretmen_sifre_label = new javax.swing.JLabel();
        ogretmen_adi_label1 = new javax.swing.JLabel();
        ogretmen_adi_textField = new javax.swing.JTextField();
        ogretmen_sifre_textField = new javax.swing.JPasswordField();
        ogretmen_giris_buton = new javax.swing.JButton();
        ana_sayfa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ogretmen_panel.setBackground(new java.awt.Color(255, 204, 204));

        ogretmen_sifre_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ogretmen_sifre_label.setText("Ogretmen Sifre : ");

        ogretmen_adi_label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ogretmen_adi_label1.setText("Ogretmen Sicili : ");

        ogretmen_adi_textField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ogretmen_sifre_textField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ogretmen_sifre_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogretmen_sifre_textFieldActionPerformed(evt);
            }
        });

        ogretmen_giris_buton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ogretmen_giris_buton.setText("Ogretmen Giris");
        ogretmen_giris_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogretmen_giris_butonActionPerformed(evt);
            }
        });

        ana_sayfa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ana_sayfa.setText("Ana Sayfa");
        ana_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_sayfaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ogretmen Giris Ekrani");

        javax.swing.GroupLayout ogretmen_panelLayout = new javax.swing.GroupLayout(ogretmen_panel);
        ogretmen_panel.setLayout(ogretmen_panelLayout);
        ogretmen_panelLayout.setHorizontalGroup(
            ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ogretmen_panelLayout.createSequentialGroup()
                .addGap(0, 189, Short.MAX_VALUE)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ogretmen_adi_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogretmen_sifre_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ogretmen_sifre_textField)
                    .addComponent(ogretmen_adi_textField)
                    .addComponent(ogretmen_giris_buton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(106, 106, 106))
            .addGroup(ogretmen_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ana_sayfa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ogretmen_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        ogretmen_panelLayout.setVerticalGroup(
            ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ogretmen_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ana_sayfa)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogretmen_adi_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogretmen_adi_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogretmen_sifre_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogretmen_sifre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(ogretmen_giris_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ogretmen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ogretmen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ogretmen_sifre_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogretmen_sifre_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ogretmen_sifre_textFieldActionPerformed

    private void ogretmen_giris_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogretmen_giris_butonActionPerformed

        String kullaniciAdi = ogretmen_adi_textField.getText();
        String sifreString = new String(ogretmen_sifre_textField.getPassword());

        try {
            // Şifreyi integer olarak parse etme
            int sifre = Integer.parseInt(sifreString);

            // JDBC sürücüsünü yükleme
            Class.forName("org.postgresql.Driver");

            // Veritabanına bağlanma
            Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");

            // SQL sorgusu
            String sql = "SELECT * FROM ogretmen WHERE ogretmen_sicil_no=? AND ogretmen_sifresi=?";

            // PreparedStatement oluşturma
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, Integer.parseInt(kullaniciAdi));
            preparedStatement.setInt(2, sifre); // Integer olarak set etme

            // Sorguyu çalıştırma ve sonucu alma
            ResultSet resultSet = preparedStatement.executeQuery();
            int yonetici_ogrenci_talep_sayisi = 1;
            // Sonuçları kontrol etme
            if (resultSet.next()) {
                System.out.println("Giriş Başarılı");
                String sqlyon = "SELECT yonetici_ogrenci_talep_sayisi FROM yonetici ";
                PreparedStatement preparedStatement2 = connection.prepareStatement(sqlyon);
                ResultSet resultSet2 = preparedStatement2.executeQuery();
                if (resultSet2.next()) {

                    yonetici_ogrenci_talep_sayisi =Integer.parseInt(resultSet2.getString("yonetici_ogrenci_talep_sayisi")) ;
                }
                //gretmen_giris_ekrani.setData(sql);
                this.setVisible(false);
                System.out.println("kullaniciAdi"+kullaniciAdi);
                new ogretmen_panel(kullaniciAdi,yonetici_ogrenci_talep_sayisi).setVisible(true);

            } else {
                System.out.println("Kullanıcı adı veya şifre yanlış");
                JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

            }

            // Bağlantıyı kapatma
            connection.close();
        } catch (NumberFormatException e) {
            System.out.println("Geçersiz şifre formatı: " + e.getMessage());
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Veritabanı hatası: " + e.getMessage());
        }


    }//GEN-LAST:event_ogretmen_giris_butonActionPerformed

    private void ana_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_sayfaActionPerformed
        this.setVisible(false);
        new kullanici_secim_ekrani().setVisible(true);
    }//GEN-LAST:event_ana_sayfaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogretmen_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogretmen_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogretmen_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogretmen_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogretmen_giris_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ana_sayfa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ogretmen_adi_label1;
    private javax.swing.JTextField ogretmen_adi_textField;
    private javax.swing.JButton ogretmen_giris_buton;
    private javax.swing.JPanel ogretmen_panel;
    private javax.swing.JLabel ogretmen_sifre_label;
    private javax.swing.JPasswordField ogretmen_sifre_textField;
    // End of variables declaration//GEN-END:variables
}
