/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 90507
 */
public class yonetici_ogretmen_ekleme_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form yonetici_ogretmen_ekleme_ekrani
     */
    public yonetici_ogretmen_ekleme_ekrani() {

        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ana_sayfa1 = new javax.swing.JButton();
        bir_onceki_sayfa = new javax.swing.JButton();
        ogretmen_sicil_label = new javax.swing.JLabel();
        ogretmen_sicil_textF = new javax.swing.JTextField();
        ogretmen_adi_label = new javax.swing.JLabel();
        ogretmen_soyadi_label = new javax.swing.JLabel();
        ogretmen_ilgialani_label = new javax.swing.JLabel();
        ogretmen_soyadi_textF = new javax.swing.JTextField();
        ogretmen_adi_textF = new javax.swing.JTextField();
        ogretmen_ilgialani_textF = new javax.swing.JTextField();
        ogretmen_ekle_buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dersleri_goruntule_table = new javax.swing.JTable();
        ogretmen_sifre_label = new javax.swing.JLabel();
        ogretmen_sifre_textF = new javax.swing.JTextField();
        dersleri_getir_buton = new javax.swing.JButton();
        ogretmen_sifre_label1 = new javax.swing.JLabel();
        ogretmen_kontenjan_textF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        ana_sayfa1.setText("Ana Sayfa");
        ana_sayfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_sayfa1ActionPerformed(evt);
            }
        });

        bir_onceki_sayfa.setText("Bir Önceki sayfa");
        bir_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bir_onceki_sayfaActionPerformed(evt);
            }
        });

        ogretmen_sicil_label.setText("Ogretmen Sicili : ");

        ogretmen_adi_label.setText("Ogretmen Adi : ");

        ogretmen_soyadi_label.setText("Ogretmen Soyadi : ");

        ogretmen_ilgialani_label.setText("Ogretmen İlgi Alani : ");

        ogretmen_ekle_buton.setText("Ogretmen Ekle");
        ogretmen_ekle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogretmen_ekle_butonActionPerformed(evt);
            }
        });

        dersleri_goruntule_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DersKodu", "DersAdi"
            }
        ));
        jScrollPane1.setViewportView(dersleri_goruntule_table);

        ogretmen_sifre_label.setText("Ogretmen Sifre : ");

        dersleri_getir_buton.setText("Dersleri Getir");
        dersleri_getir_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersleri_getir_butonActionPerformed(evt);
            }
        });

        ogretmen_sifre_label1.setText("Ogretmen Kontenjan : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ana_sayfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bir_onceki_sayfa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogretmen_ilgialani_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ogretmen_ilgialani_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogretmen_adi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ogretmen_adi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogretmen_soyadi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ogretmen_soyadi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogretmen_sicil_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ogretmen_sicil_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogretmen_sifre_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ogretmen_kontenjan_textF1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ogretmen_sifre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ogretmen_sifre_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(dersleri_getir_buton)
                                .addGap(126, 126, 126)))))
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(ogretmen_ekle_buton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana_sayfa1)
                    .addComponent(bir_onceki_sayfa))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogretmen_sicil_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogretmen_sicil_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dersleri_getir_buton))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ogretmen_adi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogretmen_adi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ogretmen_soyadi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogretmen_soyadi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ogretmen_ilgialani_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogretmen_ilgialani_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ogretmen_sifre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogretmen_sifre_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ogretmen_sifre_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogretmen_kontenjan_textF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ogretmen_ekle_buton)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ana_sayfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_sayfa1ActionPerformed
        String message = "Ana sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new kullanici_secim_ekrani().setVisible(true);
    }//GEN-LAST:event_ana_sayfa1ActionPerformed

    private void bir_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bir_onceki_sayfaActionPerformed
        String message = "Bir önceki sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new yonetici_panel().setVisible(true);
    }//GEN-LAST:event_bir_onceki_sayfaActionPerformed

    private void ogretmen_ekle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogretmen_ekle_butonActionPerformed

        int selectedRow = dersleri_goruntule_table.getSelectedRow();
        String dersKodu = "", ogretmen_sicili = "";
        int talepsayi = 0;
        if (selectedRow != -1) {
            // Seçilen satırdan öğrenci sicil numarasını al
            Object dersKoduObject = dersleri_goruntule_table.getValueAt(selectedRow, 0);
            dersKodu = dersKoduObject != null ? dersKoduObject.toString() : "";

            Boolean flagInt = true;
            String ogretmenAdi = ogretmen_adi_textF.getText();
            String ogretmenSoyadi = ogretmen_soyadi_textF.getText();
            int sifre = 0;
            String ogretmenilgiAlani = ogretmen_ilgialani_textF.getText();
            String kontenjan = ogretmen_kontenjan_textF1.getText();
            String sicilS = ogretmen_sicil_textF.getText();
            String sifreS = ogretmen_sifre_textF.getText();
            String kontenjanS = ogretmen_kontenjan_textF1.getText();

            int ogretmenSicilNumarasi = 0;
            try {
                ogretmenSicilNumarasi = Integer.parseInt(ogretmen_sicil_textF.getText());

            } catch (Exception e) {
                flagInt = false;
                JOptionPane.showMessageDialog(null, "Lütfen sicil numarasını sadece sayılardan oluşacak şekilde girin", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

            }
            try {
                sifre = Integer.parseInt(ogretmen_sifre_textF.getText());
            } catch (Exception e) {
                flagInt = false;
                JOptionPane.showMessageDialog(null, "Lütfen şifreyi sadece sayılardan oluşacak şekilde girin", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

            }
            try {
                sifre = Integer.parseInt(kontenjan);
            } catch (Exception e) {
                flagInt = false;
                JOptionPane.showMessageDialog(null, "Lütfen kontenjan bilgisi sadece sayılardan oluşacak şekilde girin", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

            }

            if (kontenjanS == null || kontenjanS.trim().isEmpty() || sicilS == null || sicilS.trim().isEmpty() || ogretmenAdi == null || ogretmenAdi.trim().isEmpty() || ogretmenSoyadi == null || ogretmenSoyadi.trim().isEmpty() || sifreS == null || sifreS.trim().isEmpty()) {
                flagInt = false;
                JOptionPane.showMessageDialog(null, "Lütfen degerleri doldurdugunuzdan emin olun ", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

            }

            try {

                if (flagInt) {
                    Class.forName("org.postgresql.Driver");

                    // Veritabanına bağlanma
                    Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");
                    Boolean flag = false;
                    String sicilsql = "select ogretmen_sicil_no from ogretmen ";
                    PreparedStatement preparedStatement211 = connection.prepareStatement(sicilsql);
                    ResultSet resultSet211 = preparedStatement211.executeQuery();

                    while (resultSet211.next()) {
                        if (ogretmenSicilNumarasi == resultSet211.getInt("ogretmen_sicil_no")) {
                            flag = true;
                            break;
                        }
                    }

                    if (flag) {
                        JOptionPane.showMessageDialog(null, "Girilen ogretmen sicili başka bir ogretmene ait lütfen sicil num degiştirip tekrar deneyin!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        String insertSQL = "INSERT INTO ogretmen (ogretmen_sicil_no, ogretmen_adi, ogretmen_soyadi, ogretmen_ilgi_alanlari, ogretmen_sifresi,ogretmen_kontenjan_bilgisi,ogretmen_ders_kodu) VALUES (?, ?, ?, ?, ? ,?,?)";

                        try ( PreparedStatement preparedStatement = connection.prepareStatement(insertSQL)) {
                            // PreparedStatement parametrelerine değerleri yerleştir
                            preparedStatement.setInt(1, ogretmenSicilNumarasi);
                            preparedStatement.setString(2, ogretmenAdi);
                            preparedStatement.setString(3, ogretmenSoyadi);
                            preparedStatement.setString(4, ogretmenilgiAlani);
                            preparedStatement.setInt(5, sifre);
                            preparedStatement.setInt(6, Integer.parseInt(kontenjan));
                            preparedStatement.setString(7, dersKodu);

                            int affectedRows = preparedStatement.executeUpdate();
                            if (affectedRows > 0) {
                                System.out.println("Öğretmen başarıyla eklendi.");
                                JOptionPane.showMessageDialog(null, "Öğretmen başarıyla eklendi.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

                            } else {
                                System.out.println("Öğretmen eklenirken hata oluştu.");
                                JOptionPane.showMessageDialog(null, "Öğretmen eklenirken hata oluştu.", "HATA", JOptionPane.ERROR_MESSAGE);

                            }
                        } catch (SQLException e) {
                            e.printStackTrace();
                            System.out.println("Veritabanı hatası: " + e.getMessage());
                        }
                    }

                    connection.close();
                }

            } catch (ClassNotFoundException | SQLException e) {
                System.out.println("Veritabanı hatası: " + e.getMessage());
            }

        } else {
            // Hiçbir satır seçilmediyse kullanıcıya uyarı verebilirsiniz
            System.out.println("Lütfen bir ders seçin.");
            JOptionPane.showMessageDialog(null, "Lütfen ders seçin", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_ogretmen_ekle_butonActionPerformed

    private void dersleri_getir_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersleri_getir_butonActionPerformed

        try {
            Class.forName("org.postgresql.Driver");

            Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");

            // Veritabanına ekleme işlemi
            String sql = " SELECT DISTINCT ders.ders_kodu as DersKodu, ders.ders_adi as DersAdi FROM ders ";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();

            ResultSetMetaData rowdata = (ResultSetMetaData) resultSet.getMetaData();
            int j = 0;
            int i = 0;
            int say = 1;
            int col = rowdata.getColumnCount();
            int k = rowdata.getColumnCount();
            String[] kolon = new String[k];
            for (j = 0; j < k; j++) {
                kolon[j] = rowdata.getColumnName(j + 1);
            }
            dersleri_goruntule_table.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{}));
            DefaultTableModel model = (DefaultTableModel) dersleri_goruntule_table.getModel();
            model.setColumnIdentifiers(kolon);
            while (resultSet.next()) {
                Object[] o = new Object[k];
                for (j = 0; j < k; j++) {
                    o[j] = resultSet.getObject(j + 1);
                }
                model.addRow(o);
                dersleri_goruntule_table.setModel(model);
            }

            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Veritabanı hatası: " + e.getMessage());
        }


    }//GEN-LAST:event_dersleri_getir_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogretmen_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogretmen_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogretmen_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogretmen_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_ogretmen_ekleme_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ana_sayfa1;
    private javax.swing.JButton bir_onceki_sayfa;
    private javax.swing.JButton dersleri_getir_buton;
    private javax.swing.JTable dersleri_goruntule_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ogretmen_adi_label;
    private javax.swing.JTextField ogretmen_adi_textF;
    private javax.swing.JButton ogretmen_ekle_buton;
    private javax.swing.JLabel ogretmen_ilgialani_label;
    private javax.swing.JTextField ogretmen_ilgialani_textF;
    private javax.swing.JTextField ogretmen_kontenjan_textF1;
    private javax.swing.JLabel ogretmen_sicil_label;
    private javax.swing.JTextField ogretmen_sicil_textF;
    private javax.swing.JLabel ogretmen_sifre_label;
    private javax.swing.JLabel ogretmen_sifre_label1;
    private javax.swing.JTextField ogretmen_sifre_textF;
    private javax.swing.JLabel ogretmen_soyadi_label;
    private javax.swing.JTextField ogretmen_soyadi_textF;
    // End of variables declaration//GEN-END:variables
}
