/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 90507
 */
public class yonetici_ogrenci_ekleme_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form yonetici_ogrenci_ekleme_ekrani
     */
    public yonetici_ogrenci_ekleme_ekrani() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ana_sayfa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ana_sayfa1 = new javax.swing.JButton();
        bir_onceki_sayfa = new javax.swing.JButton();
        ogrenci_adi_textF = new javax.swing.JTextField();
        ogrenci_adi_label = new javax.swing.JLabel();
        ogrenci_soyadi_label = new javax.swing.JLabel();
        ogrenci_soyadi_textF = new javax.swing.JTextField();
        ogrenci_sicilno_label = new javax.swing.JLabel();
        ogrenci_sicilNo_textF = new javax.swing.JTextField();
        ogrenci_ilgialani_label = new javax.swing.JLabel();
        ogrenci_ilgialani_textF = new javax.swing.JTextField();
        ogrenci_sifresi_label1 = new javax.swing.JLabel();
        ogrenci_sifresi_textF = new javax.swing.JTextField();
        ogrenci_ekle_buton = new javax.swing.JButton();

        ana_sayfa.setText("Ana Sayfa");
        ana_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_sayfaActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));
        setForeground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        ana_sayfa1.setText("Ana Sayfa");
        ana_sayfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_sayfa1ActionPerformed(evt);
            }
        });

        bir_onceki_sayfa.setText("Bir Önceki sayfa");
        bir_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bir_onceki_sayfaActionPerformed(evt);
            }
        });

        ogrenci_adi_label.setText("Ogrenci Adi :");

        ogrenci_soyadi_label.setText("Ogrenci Soyadi :");

        ogrenci_sicilno_label.setText("Ogrenci Sicili :");

        ogrenci_ilgialani_label.setText("Ogrenci İlgi Alani :");
        ogrenci_ilgialani_label.setToolTipText("");

        ogrenci_sifresi_label1.setText("Ogrenci Sifresi :");

        ogrenci_ekle_buton.setText("Ogrenci Ekle");
        ogrenci_ekle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_ekle_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ogrenci_ilgialani_label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ogrenci_soyadi_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ana_sayfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ogrenci_adi_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ogrenci_sicilno_label, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                    .addComponent(ogrenci_sifresi_label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bir_onceki_sayfa))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ogrenci_adi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ogrenci_sicilNo_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ogrenci_soyadi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ogrenci_ilgialani_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ogrenci_sifresi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(ogrenci_ekle_buton)))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana_sayfa1)
                    .addComponent(bir_onceki_sayfa))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrenci_sicilno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_sicilNo_textF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrenci_adi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_adi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrenci_soyadi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_soyadi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrenci_sifresi_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_sifresi_textF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ogrenci_ilgialani_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_ilgialani_textF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(ogrenci_ekle_buton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ana_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_sayfaActionPerformed
        String message = "Ana sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new kullanici_secim_ekrani().setVisible(true);
    }//GEN-LAST:event_ana_sayfaActionPerformed

    private void ana_sayfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_sayfa1ActionPerformed
        String message = "Ana sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new kullanici_secim_ekrani().setVisible(true);
    }//GEN-LAST:event_ana_sayfa1ActionPerformed

    private void bir_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bir_onceki_sayfaActionPerformed
        String message = "Bir önceki sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new yonetici_panel().setVisible(true);
    }//GEN-LAST:event_bir_onceki_sayfaActionPerformed

    private void ogrenci_ekle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_ekle_butonActionPerformed

        Boolean flagInt = true;
        String ogrenciAdi = ogrenci_adi_textF.getText();
        String ogrenciSoyadi = ogrenci_soyadi_textF.getText();
        String sifreS = ogrenci_sifresi_textF.getText();
        String sicilS = ogrenci_sicilNo_textF.getText();
        int sifre = 0;
        String ilgiAlani = ogrenci_ilgialani_textF.getText();
        int ogrenciSicilNumarasi = 0;
        try {
            ogrenciSicilNumarasi = Integer.parseInt(ogrenci_sicilNo_textF.getText());

        } catch (Exception e) {
            flagInt = false;
            JOptionPane.showMessageDialog(null, "Lütfen sicil numarasını sadece sayılardan oluşacak şekilde girin", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

        }
        try {
            sifre = Integer.parseInt(ogrenci_sifresi_textF.getText());
        } catch (Exception e) {
            flagInt = false;
            JOptionPane.showMessageDialog(null, "Lütfen şifreyi sadece sayılardan oluşacak şekilde girin", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

        }

        if (sicilS == null || sicilS.trim().isEmpty() || ogrenciAdi == null || ogrenciAdi.trim().isEmpty() || ogrenciSoyadi == null || ogrenciSoyadi.trim().isEmpty() || sifreS == null || sifreS.trim().isEmpty()) {
            flagInt = false;
            JOptionPane.showMessageDialog(null, "Lütfen degerleri doldurdugunuzdan emin olun ", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("gui.yonetici_ogrenci_ekleme_ekrani.ogrenci_ekle_butonActionPerformed()");
        }

        try {

            if (flagInt) {

                Class.forName("org.postgresql.Driver");

                // Veritabanına bağlanma
                Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");
                Boolean flag = false;
                String sicilsql = "select ogrenci_sicil_num from ogrenci ";
                PreparedStatement preparedStatement211 = connection.prepareStatement(sicilsql);
                ResultSet resultSet211 = preparedStatement211.executeQuery();

                while (resultSet211.next()) {
                    if (ogrenciSicilNumarasi == resultSet211.getInt("ogrenci_sicil_num")) {
                        flag = true;
                        break;
                    }
                }

                if (flag) {
                    JOptionPane.showMessageDialog(null, "Girilen ögrenci sicili başka bir ögrenciye ait lütfen sicil num degiştirip tekrar deneyin!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    String insertSQL = "INSERT INTO ogrenci (ogrenci_sicil_num, ogrenci_adi, ogrenci_soyadi, ogrenci_ilgi_alani, ogrenci_sifresi,ogrenci_anlasma_durumu,ogrenci_anlasma_talep_sayisi) VALUES (?, ?, ?, ?, ?,? ,?)";

                    try ( PreparedStatement preparedStatement = connection.prepareStatement(insertSQL)) {
                        // PreparedStatement parametrelerine değerleri yerleştir
                        preparedStatement.setInt(1, ogrenciSicilNumarasi);
                        preparedStatement.setString(2, ogrenciAdi);
                        preparedStatement.setString(3, ogrenciSoyadi);
                        preparedStatement.setString(4, ilgiAlani);
                        preparedStatement.setInt(5, sifre);
                        preparedStatement.setString(6, "A");
                        preparedStatement.setInt(7, 0);
                        int affectedRows = preparedStatement.executeUpdate();
                        if (affectedRows > 0) {
                            System.out.println("Öğrenci başarıyla eklendi.");
                            JOptionPane.showMessageDialog(null, "Öğrenci başarıyla eklendi.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

                        } else {
                            System.out.println("Öğrenci eklenirken hata oluştu.");
                            JOptionPane.showMessageDialog(null, "Öğrenci eklenirken hata oluştu.", "HATA", JOptionPane.ERROR_MESSAGE);

                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                        System.out.println("Veritabanı hatası: " + e.getMessage());
                    }
                }

                connection.close();
            }

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Veritabanı hatası: " + e.getMessage());
        }


    }//GEN-LAST:event_ogrenci_ekle_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogrenci_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogrenci_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogrenci_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_ogrenci_ekleme_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_ogrenci_ekleme_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ana_sayfa;
    private javax.swing.JButton ana_sayfa1;
    private javax.swing.JButton bir_onceki_sayfa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ogrenci_adi_label;
    private javax.swing.JTextField ogrenci_adi_textF;
    private javax.swing.JButton ogrenci_ekle_buton;
    private javax.swing.JLabel ogrenci_ilgialani_label;
    private javax.swing.JTextField ogrenci_ilgialani_textF;
    private javax.swing.JTextField ogrenci_sicilNo_textF;
    private javax.swing.JLabel ogrenci_sicilno_label;
    private javax.swing.JLabel ogrenci_sifresi_label1;
    private javax.swing.JTextField ogrenci_sifresi_textF;
    private javax.swing.JLabel ogrenci_soyadi_label;
    private javax.swing.JTextField ogrenci_soyadi_textF;
    // End of variables declaration//GEN-END:variables
}
