/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 90507
 */
public class yonetici_belirli_derslere_gore_ata_ekrani extends javax.swing.JFrame {

    private static int counter = 0;

    /**
     * Creates new form yonetici_belirli_derslere_gore_ata_ekrani
     */
    public yonetici_belirli_derslere_gore_ata_ekrani() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dersleri_getir_buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dersleri_geti_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        bir_onceki_sayfa = new javax.swing.JButton();
        ana_sayfa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        dersleri_getir_buton.setText("Dersleri Getir");
        dersleri_getir_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersleri_getir_butonActionPerformed(evt);
            }
        });

        dersleri_geti_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ders Adı", "Ders Kodu", "Ders Kredisi"
            }
        ));
        jScrollPane1.setViewportView(dersleri_geti_table);

        jButton1.setText("Secilen dersi veren hocanın kontenjanı göre ata");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bir_onceki_sayfa.setText("Bir Önceki sayfa");
        bir_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bir_onceki_sayfaActionPerformed(evt);
            }
        });

        ana_sayfa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ana_sayfa.setText("Ana Sayfa");
        ana_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_sayfaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dersleri_getir_buton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ana_sayfa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bir_onceki_sayfa)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bir_onceki_sayfa)
                    .addComponent(ana_sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dersleri_getir_buton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dersleri_getir_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersleri_getir_butonActionPerformed
        try {
            Class.forName("org.postgresql.Driver");

            // Veritabanına bağlanma
            Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");

            // Veritabanına ekleme işlemi
            String sql = "SELECT  d.ders_adi as DersAdi, d.ders_kodu as DersKodu , d.ders_kredi as DersKredisi FROM ogrenci o JOIN ders d ON o.ogrenci_ders_kodu = d.ders_kodu WHERE (o.ogrenci_ogretmen_sicil_num IS NULL OR o.ogrenci_anlasma_durumu != 'B') AND o.ogrenci_sicil_num IS NOT NULL AND o.ogrenci_ders_kodu IS NOT NULL ORDER BY d.ders_adi DESC ";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();

            ResultSetMetaData rowdata = (ResultSetMetaData) resultSet.getMetaData();
            int j = 0;
            int i = 0;
            int say = 1;
            int col = rowdata.getColumnCount();
            int k = rowdata.getColumnCount();
            String[] kolon = new String[k];
            for (j = 0; j < k; j++) {
                kolon[j] = rowdata.getColumnName(j + 1);
            }
            dersleri_geti_table.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{}));
            DefaultTableModel model = (DefaultTableModel) dersleri_geti_table.getModel();
            model.setColumnIdentifiers(kolon);
            while (resultSet.next()) {
                Object[] o = new Object[k];
                for (j = 0; j < k; j++) {
                    o[j] = resultSet.getObject(j + 1);
                }
                model.addRow(o);
                dersleri_geti_table.setModel(model);
            }
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Veritabanı hatası: " + e.getMessage());
        }
    }//GEN-LAST:event_dersleri_getir_butonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        counter = counter + 1;
        String ogrenciDersKoduS = "";

        int selectedRow = dersleri_geti_table.getSelectedRow();

        if (counter < 6) {
            if (selectedRow != -1) {
                // Seçilen satırdan öğrenci sicil numarasını al

                Object ogrenciDersObject = dersleri_geti_table.getValueAt(selectedRow, 1);
                ogrenciDersKoduS = ogrenciDersObject != null ? ogrenciDersObject.toString() : "";

                try {
                    Class.forName("org.postgresql.Driver");
                    Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");
                    String sql2 = "select ogretmen_sicil_no , ogretmen_kontenjan_bilgisi from ogretmen where ogretmen_ders_kodu = ?  and ogretmen_kontenjan_bilgisi > 0 ";
                    PreparedStatement preparedStatement7 = connection.prepareStatement(sql2);
                    preparedStatement7.setString(1, ogrenciDersKoduS);
                    ResultSet resultSet2 = preparedStatement7.executeQuery();
                    while (resultSet2.next()) {
                        int ogretmen_kontenjan_bilgisi = resultSet2.getInt("ogretmen_kontenjan_bilgisi");
                        int kontenjan = ogretmen_kontenjan_bilgisi;
                        int ogretmen_sicil_no = resultSet2.getInt("ogretmen_sicil_no");

                        String sql = "select ogrenci_sicil_num ,ogrenci_ders_kodu from ogrenci WHERE (ogrenci_ogretmen_sicil_num IS NULL OR ogrenci_anlasma_durumu != 'B') AND ogrenci_sicil_num IS NOT NULL AND ogrenci_ders_kodu IS NOT NULL and ogrenci_ders_kodu = ?";
                        PreparedStatement preparedStatement9 = connection.prepareStatement(sql);
                        preparedStatement9.setString(1, ogrenciDersKoduS);
                        ResultSet resultSet = preparedStatement9.executeQuery();
                        while (resultSet.next()) {
                            if (kontenjan > 0) {
                                int ogrenci_sicil_num = resultSet.getInt("ogrenci_sicil_num");
                                kontenjan = kontenjan - 1;
                                String sql3 = "UPDATE ogrenci SET   ogrenci_anlasma_durumu= 'B' , ogrenci_ogretmen_sicil_num=?  WHERE ogrenci_sicil_num = ? AND ogrenci_ders_kodu = ? and ogrenci_ogretmen_sicil_num is null ";
                                PreparedStatement preparedStatement2 = connection.prepareStatement(sql3);
                                preparedStatement2.setInt(1, ogretmen_sicil_no);
                                preparedStatement2.setInt(2, ogrenci_sicil_num);
                                preparedStatement2.setString(3, ogrenciDersKoduS);
                                preparedStatement2.executeUpdate();

                                String sql11 = " UPDATE ogretmen SET  ogretmen_kontenjan_bilgisi=? WHERE ogretmen_sicil_no=?  and ogretmen_ders_kodu=? ";
                                PreparedStatement preparedStatement = connection.prepareStatement(sql11);
                                preparedStatement.setInt(1, kontenjan);
                                preparedStatement.setInt(2, ogretmen_sicil_no);
                                preparedStatement.setString(3, ogrenciDersKoduS);
                                preparedStatement.executeUpdate();
                            }
                        }
                    }
                    connection.close();
                    // Veritabanına bağlanma
                    // Veritabanına ekleme işlemi
                    JOptionPane.showMessageDialog(this, "Ders atanmıştır", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
                    dersleri_getir_butonActionPerformed(evt);
                } catch (ClassNotFoundException | SQLException e) {
                    System.out.println("Veritabanı hatası: " + e.getMessage());
                    JOptionPane.showMessageDialog(this, "Ders atanmada sorun oldu", "Hata", JOptionPane.ERROR_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(this, "Lütfen bir öğrenci seçin ve bir hoca seçin.", "Hata", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "5 kez bu işlemi yapabilirsiniz. Yönetici ekranına yönlendiriliyorsunuz", "Hata", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
            new yonetici_panel().setVisible(true);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void bir_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bir_onceki_sayfaActionPerformed
        String message = "Bir önceki sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new yonetici_panel().setVisible(true);
    }//GEN-LAST:event_bir_onceki_sayfaActionPerformed

    private void ana_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_sayfaActionPerformed
        String message = "Ana sayfaya yonlendiriliyorsunuz.";
        JOptionPane.showMessageDialog(null, message, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

        this.setVisible(false);
        new kullanici_secim_ekrani().setVisible(true);
    }//GEN-LAST:event_ana_sayfaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_belirli_derslere_gore_ata_ekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_belirli_derslere_gore_ata_ekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_belirli_derslere_gore_ata_ekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_belirli_derslere_gore_ata_ekrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_belirli_derslere_gore_ata_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ana_sayfa;
    private javax.swing.JButton bir_onceki_sayfa;
    private javax.swing.JTable dersleri_geti_table;
    private javax.swing.JButton dersleri_getir_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
