/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 90507
 */
public class yonetici_giris_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form yonetici_giris_ekrani
     */
    public yonetici_giris_ekrani() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ogretmen_panel = new javax.swing.JPanel();
        yonetici_sifre_label = new javax.swing.JLabel();
        yonetici_adi_label = new javax.swing.JLabel();
        yonetici_sicili_textField = new javax.swing.JTextField();
        yonetici_sifre_textField = new javax.swing.JPasswordField();
        yonetici_giris_buton = new javax.swing.JButton();
        ana_sayfa = new javax.swing.JButton();
        yonetici_giris_ekrani_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        ogretmen_panel.setBackground(new java.awt.Color(204, 255, 204));

        yonetici_sifre_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yonetici_sifre_label.setText("Yonetici Sifre : ");

        yonetici_adi_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yonetici_adi_label.setText("Yonetici Sicili : ");

        yonetici_sicili_textField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        yonetici_sifre_textField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yonetici_sifre_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yonetici_sifre_textFieldActionPerformed(evt);
            }
        });

        yonetici_giris_buton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yonetici_giris_buton.setText("Yonetici Giris");
        yonetici_giris_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yonetici_giris_butonActionPerformed(evt);
            }
        });

        ana_sayfa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ana_sayfa.setText("Ana Sayfa");
        ana_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ana_sayfaActionPerformed(evt);
            }
        });

        yonetici_giris_ekrani_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        yonetici_giris_ekrani_label.setText("Yonetici Giris Ekrani");

        javax.swing.GroupLayout ogretmen_panelLayout = new javax.swing.GroupLayout(ogretmen_panel);
        ogretmen_panel.setLayout(ogretmen_panelLayout);
        ogretmen_panelLayout.setHorizontalGroup(
            ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ogretmen_panelLayout.createSequentialGroup()
                .addGap(0, 189, Short.MAX_VALUE)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yonetici_adi_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yonetici_sifre_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yonetici_sifre_textField)
                    .addComponent(yonetici_sicili_textField)
                    .addComponent(yonetici_giris_buton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(106, 106, 106))
            .addGroup(ogretmen_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ana_sayfa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ogretmen_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yonetici_giris_ekrani_label, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        ogretmen_panelLayout.setVerticalGroup(
            ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ogretmen_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ana_sayfa)
                .addGap(26, 26, 26)
                .addComponent(yonetici_giris_ekrani_label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yonetici_sicili_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yonetici_adi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(ogretmen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yonetici_sifre_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yonetici_sifre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(yonetici_giris_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ogretmen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ogretmen_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yonetici_sifre_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yonetici_sifre_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yonetici_sifre_textFieldActionPerformed

    private void yonetici_giris_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yonetici_giris_butonActionPerformed

        String kullaniciAdi = yonetici_sicili_textField.getText();
        String sifreString = new String(yonetici_sifre_textField.getPassword());

        try {
            // Şifreyi integer olarak parse etme
            int sifre = Integer.parseInt(sifreString);

            // JDBC sürücüsünü yükleme
            Class.forName("org.postgresql.Driver");

            // Veritabanına bağlanma
            Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5433/esin", "postgres", "12345");

            // SQL sorgusu
            String sql = "SELECT * FROM yonetici WHERE yonetici_id=? AND yonetici_sifresi=?";

            // PreparedStatement oluşturma
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, Integer.parseInt(kullaniciAdi));
            preparedStatement.setInt(2, sifre); // Integer olarak set etme

            // Sorguyu çalıştırma ve sonucu alma
            ResultSet resultSet = preparedStatement.executeQuery();

            // Sonuçları kontrol etme
            if (resultSet.next()) {
                System.out.println("Giriş Başarılı");
                // Burada yeni panele yönlendirme veya diğer işlemleri yapabilirsiniz.
                this.setVisible(false);
                new yonetici_panel().setVisible(true);
            } else {
                System.out.println("Kullanıcı adı veya şifre yanlış");
                JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);

            }

            // Bağlantıyı kapatma
            connection.close();
        } catch (NumberFormatException e) {
            System.out.println("Geçersiz şifre formatı: " + e.getMessage());
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Veritabanı hatası: " + e.getMessage());
        }

    }//GEN-LAST:event_yonetici_giris_butonActionPerformed

    private void ana_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ana_sayfaActionPerformed
        this.setVisible(false);
        new kullanici_secim_ekrani().setVisible(true);
    }//GEN-LAST:event_ana_sayfaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_giris_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ana_sayfa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel ogretmen_panel;
    private javax.swing.JLabel yonetici_adi_label;
    private javax.swing.JButton yonetici_giris_buton;
    private javax.swing.JLabel yonetici_giris_ekrani_label;
    private javax.swing.JTextField yonetici_sicili_textField;
    private javax.swing.JLabel yonetici_sifre_label;
    private javax.swing.JPasswordField yonetici_sifre_textField;
    // End of variables declaration//GEN-END:variables
}
